### PR TITLE
Setup testing framework

### PR DESCRIPTION
**Pull request by rejeep**
This PR only contains an empty skeleton for writing unit and integration tests. I don't see any point in writing tests for the current code. But as soon as new code is written, tests for that should be written.

### CODE REVIEW

**Comment by scottaj** [comment]
I got an error when I pulled this down and ran `make`

```
In end of data:
shut-up.el:150:1:Warning: the following functions are not known to be defined:
    shut-up-write-region-original, shut-up-load-original
Wrote /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up.elc
Done (Total of 2 files compiled, 1 skipped)
Generating autoloads for package-build.el...
Generating autoloads for package-build.el...done
Saving file /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build-autoloads.el...
Wrote /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build-autoloads.el
(No changes need to be saved)
Checking /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701...
Compiling /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build-autoloads.el...
Compiling /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build-pkg.el...
Wrote /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build-pkg.elc
Compiling /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build.el...
Wrote /Users/ajs/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160430.1701/package-build.elc
Done (Total of 2 files compiled, 1 skipped)
Warning: Lisp directory `/usr/local/Cellar/emacs/24.5/share/emacs/24.5/lisp/emacs-parallel': No such file or directory
cask exec: error: [Errno 2] No such file or directory
make: *** [unit] Error 1
```

The only setup I did was to run `brew install cask`. Is there more setup I need to do? Can you add some docs to the README if so?



Some other thoughts:
1. This is great in general, If I get some time soon, I'll take care of backfilling coverage for existing code.
2. Does cucumber give us some type of advantage? Is there a repo of built in steps for doing common tasks in emacs? TBH I'm not a big fan of cucumber so I would want there to be some value add if that is what we are going to use.

**Comment by scottaj** [comment]
Also, is there a travis build for this initial setup? Do you have a link for that?

**Comment by rejeep** [comment]
Can you try installing Cask the command below and then run the install command again:

```bash
$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
```

2) It's not Cucumber, but an Emacs port called [Ecukes](https://github.com/ecukes/ecukes). There is a repository called [Espuds](https://github.com/ecukes/espuds) with common step definitions.

It's up to you how you want to test the project, but I definitely think there should be tests. Take a look at some Ecukes tests I wrote for my mocha.el mode here: https://github.com/rejeep/mocha.el-old/blob/master/features/run.feature 

I test all my interactive modes using Ecukes (and also with unit testing). I think it's a great and easy way to make sure everything is working. The test doesn't have to be very specific, but make sure everything work and then the unit tests can test the details.

> Also, is there a travis build for this initial setup?

I think you must enable this project on Travis for that.

**Comment by scottaj** [comment]
Ah, the step I was missing was that I needed to run `cask install`, as long as i do that the homebrew version of cask works fine. The first run I did didn't give me feedback that I needed to do that though.

Can you add that step to the README?

I totally agree we should have tests, I have had bad experiences in the past with cucumber, but it looks like that is a pretty mature project with lots of good prebuilt stuff so I am okay with it. 

Once the README is updated, I am good with merging this.

I'll also go ahead and make you a contributor to the project so that you can merge stuff yourself, though I would still like to do a PR flow from both of us for new stuff going in so we can keep track of it.

Sound good?

**Comment by rejeep** [comment]
> The first run I did didn't give me feedback that I needed to do that though.

Yepp, that's why I wanted you to run from master, but I later realised that [the improved error message branch](https://github.com/cask/cask/pull/349) had not been merged yet.

> Can you add that step to the README?

Yes, forced pushed the previous commit.

> I have had bad experiences in the past with cucumber, but it looks like that is a pretty mature project with lots of good prebuilt stuff so I am okay with it.

I'm not very fond of Cucumber either, but Ecukes has helped my tons in writing 20+ Emacs packages. 😄 

I'm also the creator and maintainer of that package (and Cask, Ert runner and Evm, which are also part of this PR), so we have nice control.

> Sound good?

Definitely, pull requests is IMO always the way to go!

**Pull request merged**
